name: Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/argo-cd/argo-cd
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.12'
      - uses: actions/checkout@master
        with:
          path: src/github.com/vathsalashetty25/go-swagger
      - uses: crazy-max/ghaction-docker-buildx@v3.2.0
        with:
          buildx-version: v0.4.1
       

       # get image tag
      - run: echo ::set-output name=tag::$(cat ./VERSION)-${GITHUB_SHA::8}
        working-directory: ./src/github.com/vathsalashetty25/go-swagger
        id: image       
      # build
      - run: |
          
          docker build -t swagger .
          docker tag swagger docker.pkg.github.com/vathsalashetty25/repo-for-images/swagger:latest
          
        working-directory: ./src/github.com/vathsalashetty25/go-swagger
      # publish
      - run: |
          docker login docker.pkg.github.com --username $USERNAME --password $PASSWORD
          docker push docker.pkg.github.com/vathsalashetty25/repo-for-images/swagger:${{ steps.image.outputs.tag }}
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.TOKEN }}
